---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: go-service

run:
  args:
    - -f
    - go-service/app.go
    - clean
    - package

outputs:
  - name: go-service-out
    path: go-service
